/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 7.0.1   2017-01-12

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32l1xx.h"
#include "senzor/inicia.h"
#include "displej/ili9163.h"
#include <stdio.h>
#include <math.h>
#include <string.h>
#include "senzor/buzzer.h"


#define NUMBER_OF_ULTS 3
volatile int chooseUlt = -1;
volatile uint32_t ultRawValue[NUMBER_OF_ULTS];

void ultTrigger(int index);
double getUltCm(int index);
void TIM4_IRQHandler(void);
void EXTI1_IRQHandler(void);
void Buzzer(int value[3]);

int main(void)
{
	int osx1=0,osx2=0,osx3=0,starax1=0,starax2=0,starax3=0,desatine=0;
	double vysledok = 0.0;
	char hodnota[6] = "abcdef";
	int index = 0, dlzka = 0;
	int cele[3];

	lcdInitialise(LCD_ORIENTATION1);
	lcdClearDisplay(decodeRgbValue(255, 255, 255));
	Ultrasonic_init();
	Init_Buzzer();


	lcdPutS("Prvy snimac: ", lcdTextX(0), lcdTextY(0), decodeRgbValue(0, 0, 0), decodeRgbValue(31, 31, 31));
	lcdPutS("Druhy snimac:", lcdTextX(0), lcdTextY(1), decodeRgbValue(0, 0, 0), decodeRgbValue(31, 31, 31));
	lcdPutS("Treti snimac:", lcdTextX(0), lcdTextY(2), decodeRgbValue(0, 0, 0), decodeRgbValue(31, 31, 31));

	while (1)
	{
		switch (index){
		case 0:
		  Init_interrupt1();
		  ultTrigger(index);
		  vysledok = getUltCm(index);
		  cele[index] = (int)vysledok;
		  desatine = round((vysledok-cele[index])*10);
		  sprintf(hodnota,"%d.%d",cele[index],desatine);
		  dlzka = strlen(hodnota);
		  for(dlzka;dlzka<=5;dlzka++)
		  {
		  	 hodnota[dlzka] = '0';
		  }
		  lcdPutS(hodnota, lcdTextX(15), lcdTextY(0), decodeRgbValue(0, 0, 0), decodeRgbValue(31, 31, 31));
		  osx1 = 2*cele[index];
		  if (osx1>122)
			  	  osx1 = 122;
		  if (osx1<4)
		 		  osx1 = 4;
		  index++;
		  break;
	  case 1:
		  Init_interrupt2();
		  ultTrigger(index);
		  vysledok = getUltCm(index);
		  cele[index] = (int)vysledok;
		  desatine = round((vysledok-cele[index])*10);
		  sprintf(hodnota,"%d.%d",cele[index],desatine);
		  dlzka = strlen(hodnota);
		  for(dlzka;dlzka<=5;dlzka++)
		  {
			  hodnota[dlzka]='0';
		  }
		  lcdPutS(hodnota, lcdTextX(15), lcdTextY(1), decodeRgbValue(0, 0, 0), decodeRgbValue(31, 31, 31));
		  osx2 = 2*cele[index];
		  if (osx2>122)
				  osx2=122;
		  if (osx2<4)
				  osx2=4;
		  index++;
		  break;
	  case 2:
		  Init_interrupt3();
		  ultTrigger(index);
		  vysledok = getUltCm(index);
		  cele[index] = (int)vysledok;
		  desatine = round((vysledok-cele[index])*10);
		  sprintf(hodnota,"%d.%d",cele[index],desatine);
		  dlzka = strlen(hodnota);
		  for(dlzka;dlzka<=5;dlzka++)
		  {
			  hodnota[dlzka] = '0';
		  }
		  lcdPutS(hodnota, lcdTextX(15), lcdTextY(2), decodeRgbValue(0, 0, 0), decodeRgbValue(31, 31, 31));
		  osx3 = 2*cele[index];
		  if (osx3>122)
		  		  osx3 = 122;
		  if (osx3<4)
		  		  osx3 = 4;
		  index = 0;
		  break;
	  default:
		  break;
	  }


	if(starax1 != osx1){
			lcdLine(starax1, 64, starax1, 80, decodeRgbValue(255, 255, 255));
			lcdLine(osx1, 64, osx1, 80, decodeRgbValue(0, 0, 0));
	}
	if(starax2 != osx2){
			lcdLine(starax2, 85, starax2, 101, decodeRgbValue(255, 255, 255));
			lcdLine(osx2, 85, osx2, 101, decodeRgbValue(0, 0, 0));
	}
	if(starax3 != osx3){
			lcdLine(starax3, 106, starax3, 122, decodeRgbValue(255, 255, 255));
			lcdLine(osx3, 106, osx3, 122, decodeRgbValue(0, 0, 0));
	}

	starax1 = osx1;
	starax2 = osx2;
	starax3 = osx3;



	Buzzer(cele);
  }
  return 0;
}

void ultTrigger(int index)
{
	while(chooseUlt!= -1);
	switch (index) {
	case 0:
		TIM_SetCounter(TIM4, 0);
		chooseUlt = index;
		GPIOC->BSRRL = GPIO_Pin_0;
		for (int i = 0; i < 2; i++); //cca 15 us
		GPIOC->BSRRH = GPIO_Pin_0;
		break;
	case 1:
		TIM_SetCounter(TIM4, 0);
		chooseUlt = index;
		GPIOC->BSRRL = GPIO_Pin_2;
		for (int i = 0; i < 2; i++); //cca 15 us
		GPIOC->BSRRH = GPIO_Pin_2;
		break;
	case 2:
		TIM_SetCounter(TIM4, 0);
		chooseUlt = index;
		GPIOC->BSRRL = GPIO_Pin_3;
		for (int i = 0; i < 2; i++); //cca 15 us
		GPIOC->BSRRH = GPIO_Pin_3;
		break;
	}
}

double getUltCm(int index)
{
	return ((double)ultRawValue[index])/58;
}

void TIM4_IRQHandler(void)
{
	if (TIM_GetITStatus(TIM4, TIM_IT_Update) != RESET)
	{
		TIM_ClearITPendingBit(TIM4, TIM_IT_Update);
		if(chooseUlt!=-1)
		{
			ultRawValue[chooseUlt] = 65535;
			chooseUlt = -1;
		}
	}
}

void EXTI1_IRQHandler(void)
{
	if (EXTI_GetITStatus(EXTI_Line1) != RESET) {
		if (chooseUlt == 0)
		{
			if((GPIOC->IDR & GPIO_Pin_1) && GPIO_Pin_1){
				TIM_SetCounter(TIM4, 0);
			}
			else{
				ultRawValue[chooseUlt] = TIM_GetCounter(TIM4);
				chooseUlt = -1;
			}
		}
		if (chooseUlt == 1){
			if((GPIOH->IDR & GPIO_Pin_1) && GPIO_Pin_1){
				TIM_SetCounter(TIM4, 0);
			}
			else{
				ultRawValue[chooseUlt] = TIM_GetCounter(TIM4);
				chooseUlt = -1;
			}
		}
		if (chooseUlt == 2){
			if((GPIOA->IDR & GPIO_Pin_1) && GPIO_Pin_1){
				TIM_SetCounter(TIM4, 0);
			}
			else{
				ultRawValue[chooseUlt] = TIM_GetCounter(TIM4);
				chooseUlt = -1;
			}
		}
		EXTI_ClearITPendingBit(EXTI_Line1);
	}
}

void Buzzer(int value[]){

	int min;

	if (value[0]>= value[1])
		min = value[1];
	else
		min = value[0];
	if (min >= value[2])
		min = value[2];
	if (min > 64)
		Set_None();
	if (min < 65 && min > 50)
		Set_Low();
	if (min < 51 && min > 25)
		Set_Med();
	if (min < 26)
		Set_High();

}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}
